actuator_driver:
  ros__parameters:
    cmd_topic: "/ackermann/cmd_effort"
    timeout_s: 0.5
    update_hz: 50.0

    i2c_bus: 1
    i2c_address: 64
    pwm_hz: 50.0
    osc_clock_hz: 25000000

    steering_channel: 15
    steering_min_tick: 205
    steering_center_tick: 307
    steering_max_tick: 410
    steering_inverted: false

    motor_forward_channel: 1
    motor_backward_channel: 2
    throttle_max_tick: 1638

    neutral_hold_ms: 100.0
